### PR TITLE
Review wine e2e tests

### PR DESCRIPTION
**Pull request by devskar**

### CODE REVIEW

**Comment by devskar** [comment]
Removed `uuid` package and used `fakerjs` to generate id's and other values

**Comment by devskar** [comment]
Changed syntax of describe blocks

**Comment by devskar** [comment]
Moved utils method and added tests for getting ratings where ratings actually get created before

**Comment by devskar** [comment]
Changed
```ts
.expect((response) => response.status === HttpStatus.NOT_FOUND)
```
to
```ts
.expect(HttpStatus.NOT_FOUND)
```
so status codes actually get validated

**Comment by devskar** [comment]
There were some authHeaders missing, but you couldn't notice it first because the return codes did not get validated. Also some expected response codes were wrong because they return bad request when you send no data

**Comment by devskar** [comment]
Added tests to actually check the creation of ratings and body validation

**Comment by devskar** [comment]
So I renamed add-store-to-wine.dto to update-wine.dto. For some reason u never used the add-store-wine-dto except in tests. I updated the controller and service

**Review by tschokri — APPROVED** [review]
geil

**Pull request merged**
